// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lptuwnjrtweljtgtyzvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwdHV3bmpydHdlbGp0Z3R5enZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzM5MjUsImV4cCI6MjA2MDA0OTkyNX0.7l_W81KZ3TzJbqqPl-9ZpP79T40PZHhusYjjCaRHe5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);